"""Synthesizer agent – produces the final research report."""

from __future__ import annotations

from typing import Any, Dict, Literal

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from langgraph.types import Command

from src.config import get_chat_model
from src.state import ResearchState
from src.utils.logging_setup import get_logger

log = get_logger("research_swarm.synthesizer")


def synthesizer_node(state: ResearchState) -> Command[Literal["supervisor"]]:
    """
    Synthesizer specialist.

    Generates a cited markdown report from sources, facts (with evidence), and conflicts.
    Falls back to a structured template if the LLM call fails.
    """
    goal = state.get("goal", "Unknown research goal")
    sources = state.get("sources", [])
    facts = state.get("extracted_facts", [])
    conflicts = state.get("conflicts", [])
    errors = list(state.get("errors", []))

    source_lines = []
    for i, s in enumerate(sources[:8], 1):
        title = s.title or s.url
        source_lines.append(f"{i}. [{title}]({s.url}) (quality={s.quality_score:.2f})")

    fact_lines = []
    for f in facts[:15]:
        line = (
            f"- {f.claim}: {f.value} "
            f"(conf={f.confidence:.2f}; urls={', '.join(f.source_urls[:2])})"
        )
        if f.evidence:
            ev = f.evidence.strip().replace("\n", " ")
            if len(ev) > 280:
                ev = ev[:277] + "..."
            line += f'\n  evidence: "{ev}"'
        fact_lines.append(line)
    conflict_lines = [f"- ({c.severity}) {c.description}" for c in conflicts]

    context = (
        f"Goal: {goal}\n\n"
        f"Sources ({len(sources)}):\n" + "\n".join(source_lines) + "\n\n"
        f"Facts ({len(facts)}):\n" + "\n".join(fact_lines) + "\n\n"
        f"Conflicts ({len(conflicts)}):\n"
        + ("\n".join(conflict_lines) if conflict_lines else "None")
    )

    system = (
        "You are a precise research synthesizer. "
        "Write a clear, well-structured markdown report that answers the research goal.\n\n"
        "Preferred structure:\n"
        "1. Title (H1)\n"
        "2. Executive summary (2–4 sentences)\n"
        "3. Key findings (numbered; each finding should cite a source URL and, "
        "when evidence quotes are provided, briefly reflect that evidence)\n"
        "4. Gaps / caveats (if any)\n"
        "5. Sources (numbered list with titles and URLs)\n\n"
        "Rules:\n"
        "- Prefer facts that include an evidence quote; treat facts without evidence as weaker.\n"
        "- Do not invent quotes or facts. You may lightly paraphrase claims, but do not "
        "fabricate evidence text.\n"
        "- Be honest about conflicts and thin coverage.\n"
        "- Prefer concrete claims over marketing language."
    )

    report = None
    try:
        llm = get_chat_model(temperature=0.2)
        response = llm.invoke([SystemMessage(content=system), HumanMessage(content=context)])
        report = response.content
        log.info("synthesis ok report_len=%s", len(report or ""))
    except Exception as exc:
        errors.append(f"Synthesizer LLM failed: {exc}")
        log.exception("synthesizer LLM failed")

    if not report:
        lines = [
            "# Research Report",
            "",
            f"**Goal:** {goal}",
            "",
            "## Summary",
            "Automated synthesis was unavailable. Below is a structured dump of collected material.",
            "",
            f"## Sources ({len(sources)})",
            *source_lines,
            "",
            f"## Extracted Facts ({len(facts)})",
            *fact_lines,
        ]
        if conflicts:
            lines += ["", f"## Conflicts ({len(conflicts)})", *conflict_lines]
        lines += ["", "---", "*Generated by research-swarm (fallback template)*"]
        report = "\n".join(lines)

    structured: Dict[str, Any] = {
        "goal": goal,
        "num_sources": len(sources),
        "num_facts": len(facts),
        "num_conflicts": len(conflicts),
    }

    updates = {
        "report": report,
        "structured_report": structured,
        "status": "completed",
        "messages": [AIMessage(content=f"Synthesizer: report ready ({len(report)} chars).")],
        "errors": errors,
    }
    return Command(goto="supervisor", update=updates)
