"""Synthesizer agent stub – produces the final research report."""

from __future__ import annotations

from typing import Any, Dict, Literal

from langchain_core.messages import AIMessage
from langgraph.types import Command

from src.state import ResearchState


def synthesizer_node(state: ResearchState) -> Command[Literal["supervisor"]]:
    """
    Synthesizer specialist (stub).

    In the real implementation this will generate a well-structured,
    cited markdown report (and optionally a structured JSON version)
    from the accumulated sources, facts, and conflicts.
    """
    goal = state.get("goal", "Unknown research goal")
    sources = state.get("sources", [])
    facts = state.get("extracted_facts", [])
    conflicts = state.get("conflicts", [])

    # TODO: Replace with a proper LLM call that:
    # - Writes a clear executive summary
    # - Organizes findings by theme
    # - Includes inline citations and a sources section
    # - Highlights conflicts / low-confidence claims

    report_lines = [
        f"# Research Report (Stub)",
        f"",
        f"**Goal:** {goal}",
        f"",
        f"## Summary",
        f"This is a placeholder report generated by the synthesizer stub.",
        f"Replace this logic with a real LLM synthesis step that uses the",
        f"collected sources and extracted facts.",
        f"",
        f"## Collected Sources ({len(sources)})",
    ]

    for i, src in enumerate(sources, 1):
        title = src.title or src.url
        report_lines.append(f"{i}. [{title}]({src.url}) — quality={src.quality_score:.2f}")

    report_lines.append("")
    report_lines.append(f"## Extracted Facts ({len(facts)})")
    for fact in facts:
        report_lines.append(f"- **{fact.claim}**: {fact.value} (confidence={fact.confidence:.2f})")

    if conflicts:
        report_lines.append("")
        report_lines.append(f"## Conflicts / Caveats ({len(conflicts)})")
        for c in conflicts:
            report_lines.append(f"- ({c.severity}) {c.description}")

    report_lines.append("")
    report_lines.append("---")
    report_lines.append("*Generated by research-swarm synthesizer stub*")

    report = "\n".join(report_lines)

    structured: Dict[str, Any] = {
        "goal": goal,
        "num_sources": len(sources),
        "num_facts": len(facts),
        "num_conflicts": len(conflicts),
        "stub": True,
    }

    updates = {
        "report": report,
        "structured_report": structured,
        "status": "completed",
        "messages": [
            AIMessage(
                content=f"Synthesizer (stub): produced placeholder report "
                f"({len(sources)} sources, {len(facts)} facts)."
            )
        ],
    }

    # After synthesis we still return to the supervisor so it can decide FINISH
    return Command(goto="supervisor", update=updates)
