"""Synthesizer agent – produces the final research report."""

from __future__ import annotations

from typing import Any, Dict, Literal

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from langgraph.types import Command

from src.state import ResearchState


def synthesizer_node(state: ResearchState) -> Command[Literal["supervisor"]]:
    """
    Synthesizer specialist.

    Generates a cited markdown report from the accumulated sources, facts, and conflicts.
    Falls back to a structured template if the LLM call fails.
    """
    goal = state.get("goal", "Unknown research goal")
    sources = state.get("sources", [])
    facts = state.get("extracted_facts", [])
    conflicts = state.get("conflicts", [])
    errors = list(state.get("errors", []))

    # Build compact context for the LLM
    source_lines = []
    for i, s in enumerate(sources[:8], 1):
        title = s.title or s.url
        source_lines.append(f"{i}. [{title}]({s.url}) (quality={s.quality_score:.2f})")

    fact_lines = [f"- {f.claim}: {f.value} (conf={f.confidence:.2f})" for f in facts[:15]]
    conflict_lines = [f"- ({c.severity}) {c.description}" for c in conflicts]

    context = (
        f"Goal: {goal}\n\n"
        f"Sources ({len(sources)}):\n" + "\n".join(source_lines) + "\n\n"
        f"Facts ({len(facts)}):\n" + "\n".join(fact_lines) + "\n\n"
        f"Conflicts ({len(conflicts)}):\n" + ("\n".join(conflict_lines) if conflict_lines else "None")
    )

    system = (
        "You are a precise research synthesizer. "
        "Write a clear, well-structured markdown report that answers the research goal. "
        "Include an executive summary, key findings with citations where possible, "
        "and a short sources section. Be honest about gaps or conflicts. "
        "Do not invent facts."
    )

    report = None
    try:
        llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.2)
        response = llm.invoke([SystemMessage(content=system), HumanMessage(content=context)])
        report = response.content
    except Exception as exc:
        errors.append(f"Synthesizer LLM failed: {exc}")

    # Fallback template
    if not report:
        lines = [
            f"# Research Report",
            f"",
            f"**Goal:** {goal}",
            f"",
            f"## Summary",
            f"Automated synthesis was unavailable. Below is a structured dump of collected material.",
            f"",
            f"## Sources ({len(sources)})",
            *source_lines,
            f"",
            f"## Extracted Facts ({len(facts)})",
            *fact_lines,
        ]
        if conflicts:
            lines += ["", f"## Conflicts ({len(conflicts)})", *conflict_lines]
        lines += ["", "---", "*Generated by research-swarm (fallback template)*"]
        report = "\n".join(lines)

    structured: Dict[str, Any] = {
        "goal": goal,
        "num_sources": len(sources),
        "num_facts": len(facts),
        "num_conflicts": len(conflicts),
    }

    updates = {
        "report": report,
        "structured_report": structured,
        "status": "completed",
        "messages": [
            AIMessage(
                content=f"Synthesizer: produced report ({len(sources)} sources, {len(facts)} facts)."
            )
        ],
        "errors": errors,
    }

    return Command(goto="supervisor", update=updates)
